site_name: Greenter - Facturación Electrónica en Perú
site_url: https://greenter.dev
site_description: |
  Crea facturas electrónicas siguiendo el estándar UBL 2.0, 2.1 en Perú, 
  bajo la normativa dispuesta por SUNAT
site_author: 'Giancarlos Salas'

# Repository
repo_name: 'greenter/greenter'
repo_url: 'https://github.com/thegreenter/docs'

copyright: Copyright &copy; 2020 Giancarlos Salas

nav:
    - Inicio:
      - index.md
    - Empezar:
      - Guia de Inicio: starter.md
      - Migrar a UBL 2.1: migrate2.1.md
      - Paso a Producción: production.md
      - 'Preguntas Frecuentes': faq.md
    - Ejemplos:
      - F. Exonerada: examples/exonerada.md
      - F. Gratuita: examples/gratuita.md
      - F. Descuentos: examples/descuento-linea.md
      - F. Percepción: examples/percepcion.md
      - F. Anticipos: examples/anticipo.md
      - F. Detracción: examples/detraccion.md
      - F. Exportación: examples/exportacion.md
      - F. ICBPER: examples/icbper.md
      - 'Boleta de Venta': examples/boleta.md
      - Contingencia: examples/contingencia.md
    - Referencia:
      - greenter/xml: packages/xml.md
      - greenter/xmldsig: packages/sign.md
      - greenter/ws: packages/ws.md
      - greenter/report: packages/report.md
      - 'API Referencia': https://reference.greenter.dev/

# Configuration
theme:
  name: 'material'
  custom_dir: docs/overrides
  favicon: 'img/favicon.ico'
  logo: 'img/logo.svg'
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  
  static_templates:
    - 404.html
  language: 'es'
  features:
    - tabs
  palette:
    scheme: slate
    primary: green
    accent: indigo

extra:
  manifest: 'manifest.webmanifest'
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/thegreenter
    - icon: fontawesome/brands/facebook
      link: https://fb.me/thegreenter
    - icon: fontawesome/brands/discourse
      link: https://community.greenter.dev/
  disqus: 'greenter'
  repo_project: https://github.com/thegreenter/greenter

extra_css:
  - 'css/codehilite.css'
  
extra_javascript:
  - 'js/app.js'

google_analytics:
  - UA-90097417-6
  - auto

plugins:
  - search
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - meta
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.magiclink:
      repo_url_shortener: true
  - toc:
      permalink: true
